### ISSUE TITLE
Water does not flow more than one block in vault bastion fields

### ISSUE THREAD

**Issue by Xavter** [CivClassic/Bastion#8] opened 2020-05-11 02:13 UTC
Post 1.14, water placed in or near a vault bastion field will be blocked from flowing more than a single block.

![image](https://user-images.githubusercontent.com/11353433/81518127-01107300-930b-11ea-8dbe-102ceb6e39b0.png)
![image](https://user-images.githubusercontent.com/11353433/81518139-0ec5f880-930b-11ea-942e-84d133f26aab.png)
![image](https://user-images.githubusercontent.com/11353433/81518174-29986d00-930b-11ea-8c6d-73092e80ffc6.png)
![image](https://user-images.githubusercontent.com/11353433/81518197-3ddc6a00-930b-11ea-91df-da1ca00fc116.png)

This does not affect city bastioned towns or pre-existing flowing water. It is hard to determine why sometimes it flows one block or will stop flow outside of nearby bastions.

**Comment by Maxopoly** [comment] 2020-05-11 02:14
It shouldn't flow at all

**Comment by Maxopoly** [comment] 2020-05-11 02:20
It seems like the blocks at which it spreads are consistent, so it's most likely an issue with which blocks are being looked up in the QuadTree

**Comment by Xavter** [comment] 2020-05-11 02:32
So to be clear - waterflow should be blocked entirely in vault bastion fields is intended, and waterflow happening inside of the field and water flow not happening outside of nearby fields are unintended?

**Comment by Maxopoly** [comment] 2020-05-11 02:35
> waterflow should be blocked entirely in vault bastion fields

yes, intended

> waterflow happening inside of the field

not intended

> water flow not happening outside of nearby

not intended

**Comment by Xavter** [comment] 2020-05-11 21:14
Confirmed the other issue we were uncertain about as well. In 1.12, if you were on the group and placed a water block, the water would flow. If you were not on the vault bastion group and placed a water block, it would not be placed at all. I think fixing this would be sufficient to cover up the other two issues if possible.

**Comment by Maxopoly** [comment] 2020-05-19 22:33
Previous behavior:
- Water, Pistons etc. work in bastion fields, but they can not go into a bastion field from outside of it

Current behavior
- Water and pistons don't work at all in Bastion fields

---

Reading the code it seems like the original intention was always what is now the current behavior. I suspect that fixing something else also made this work as intended, but could be wrong. Need to investigate what exactly changed compared to the 1.12 version (can use devoted repo as reference), I already did so but found nothing.

**Comment by Falvyu** [comment] 2020-07-26 23:36
Dumb idea: Why not add a permission to prevent/allow water flow in bastion fields ?

The rank system would obviously not make much sense as water flow isn't directly caused by player interaction. However, that would let players to choose whether they want to keep water flowing in their towns/vault or not, wouldn't it ?

**Comment by Maxopoly** [comment] 2020-07-26 23:39
Permissions are a per rank setting, not a per group setting. This could be implemented using https://github.com/CivClassic/NameLayer/issues/20 which is already fully implemented and working in my rewrite fork of NameLayer. I'll make a separate issue for your suggestion for now

**Comment by Maxopoly** [comment] 2020-07-27 03:51
Should be fixed by https://github.com/CivClassic/Bastion/commit/cb9858493d5342b8569e977bdecffdde6335d18b

**Closed as completed by Maxopoly** 2020-07-27 03:51 UTC
Labels: bug, regression, D2 - advanced issue
