### ISSUE TITLE
Bastions go into negative health when breaking

### ISSUE THREAD

**Issue by squareblob** [CivClassic/Bastion#18] opened 2020-08-07 03:00 UTC
- This occurs when breaking a bastion:
    - by directly mining the block the bastion goes into negative health
    - by placing blocks the bastion is destroyed yet replacing a bastion in its place shows a bastion with negative health (some players report the bastion is not destroyed and simply goes into negatives)
- Some bastions with negative health block placements, some do not (?)
- Negative reinforced bastions return to full health on server restart

This has been an issue since the 1.16 update. I will update this issue when I get a chance to test properly.

**Comment by Maxopoly** [comment] 2020-08-07 03:45
Multiple things that need to be done here, most of which are Citadel issues:

- Negative health reinforcements should never be written to the database
- Negative health reinforcements should be deleted from the database when attempting to load them
- Replacing a block where a reinforcement was should always delete the reinforcement. If a block is placed in an AIR spot and a reinforcement exists there, it should be deleted (thought that was already the case?)
- Find the exception happening when breaking the bastion. Something most be going wrong when the bastion is going below 0 health.

**Comment by Maxopoly** [comment] 2020-08-12 03:09
Should be fixed by https://github.com/CivClassic/CivModCore/commit/1195e6d6c77daaf800162608c623383541228468

**Comment by Maxopoly** [comment] 2020-08-30 13:34
Reopening as not actually fixed. This is actually not a Bastion issue, but caused by Reinforcement loaded in CMCs block tracking fallback for data in unloaded chunks and it not being properly removed/persisted.

**Comment by Maxopoly** [comment] 2020-08-30 13:34
Will likely try to tackle this myself later

**Comment by wingzero54** [comment] 2021-03-22 15:17
This was fixed, I think by [this CMC commit](https://github.com/CivClassic/CivModCore/commit/2bc0ba87eddeb7e6fbaa7614645030bf3d94b754)

**Closed as completed by wingzero54** 2021-03-22 15:17 UTC
Labels: bug, D2 - advanced issue
